//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CppGenerator v5.0.0) on 05.06.2026 07:06:15.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#include <coretypes/coretypes.h>
#include "coreobjects/permissions_internal.h"
#include <coretypes/objectptr.h>
#include <coretypes/dict_ptr.h>
#include <coretypes/string_ptr.h>
#include <coretypes/integer.h>




BEGIN_NAMESPACE_OPENDAQ


class PermissionsInternalPtr;



END_NAMESPACE_OPENDAQ

BEGIN_NAMESPACE_OPENDAQ

template <>
struct InterfaceToSmartPtr<daq::IPermissionsInternal>
{
    using SmartPtr = daq::PermissionsInternalPtr;
};


END_NAMESPACE_OPENDAQ

BEGIN_NAMESPACE_OPENDAQ



/*!
 * @brief Internal Permissions interface. It should be used only in openDAQ core implementation files.
 */

class PermissionsInternalPtr : public daq::ObjectPtr<IPermissionsInternal>
{
public:
    using daq::ObjectPtr<IPermissionsInternal>::ObjectPtr;
    //using daq::ObjectPtr<IPermissionsInternal>::operator=;



    PermissionsInternalPtr()
        : daq::ObjectPtr<IPermissionsInternal>()

    {
    }

    PermissionsInternalPtr(daq::ObjectPtr<IPermissionsInternal>&& ptr)
        : daq::ObjectPtr<IPermissionsInternal>(std::move(ptr))

    {
    }

    PermissionsInternalPtr(const daq::ObjectPtr<IPermissionsInternal>& ptr)
        : daq::ObjectPtr<IPermissionsInternal>(ptr)

    {
    }

    PermissionsInternalPtr(const PermissionsInternalPtr& other)
        : daq::ObjectPtr<IPermissionsInternal>(other)

    {
    }

    PermissionsInternalPtr(PermissionsInternalPtr&& other) noexcept
        : daq::ObjectPtr<IPermissionsInternal>(std::move(other))

    {
    }
    
    PermissionsInternalPtr& operator=(const PermissionsInternalPtr& other)
    {
        daq::ObjectPtr<IPermissionsInternal>::operator =(other);


        return *this;
    }

    PermissionsInternalPtr& operator=(PermissionsInternalPtr&& other) noexcept
    {

        daq::ObjectPtr<IPermissionsInternal>::operator =(std::move(other));

        return *this;
    }


    /*!
     * @brief Returns a dictionary of assigned permissions for each group.
     * @param permissions[out] A dictionary of assigned permissions for each group.
     */
    daq::DictPtr<daq::IString, daq::IInteger> getAssigned() const
    {
        if (this->object == nullptr)
            DAQ_THROW_EXCEPTION(daq::InvalidParameterException);

        daq::DictPtr<daq::IString, daq::IInteger> permissions;
        auto errCode = this->object->getAssigned(&permissions);
        daq::checkErrorInfo(errCode);

        return permissions;
    }

#if __has_include(<coreobjects/permissions_internal_ptr.custom.h>)
    #include <coreobjects/permissions_internal_ptr.custom.h>
#endif
};

END_NAMESPACE_OPENDAQ
